### ISSUE TITLE
Proposal to change the public URL for go-live

### ISSUE THREAD

**Issue by tyler-patterson-chr** [ch-robinson/ch-robinson.github.com#3]
I'd like to propose we reconsider the blog URL of engineering.chrobinson.com and instead consider something like:

- tech.chrobinson.com
- technology.chrobinson.com
- it.chrobinson.com

I think today "Engineering" carries a connotation of only for engineers/developers and can be perceived as excluding the other roles in our department. Considering we'd like to keep the blog topics open to all facets of our department, Agile, Infrastructure, Engineering, Networking, etc. I think a universal name would keep it inclusive.

**Comment by kyle-spitzer-chr** [comment]
If we change it, my vote would be technology.chrobinson.com.
